### ISSUE TITLE
if a page appear and disappear

### ISSUE THREAD

**Issue by xhzengAIB** [TaPhuocHai/PHPageScrollView#1]
@taphuochai 
Thanks your open source,
How do I know if a page appear and disappear?

Jack

**Comment by engineeringkyle** [comment]
Use the delegate method didScrollToPageAtIndex.
For example:
If you swipe over and to the first index (index 0) that means the second index disappeared (index 1) and the first index appeared. @xhzengAIB

**Comment by xhzengAIB** [comment]
ok! Thank you! I close this issue
